### PR TITLE
Custom fields in timeentries, some Clones

### PR DESCRIPTION
**Pull request by michael-fuchs**
Hi Matthias, hi Yuki, I added a little code to your redmine-api to make it suitable for our needs at my company. I used it to sync time entries from our own redmine with worklogs of our customer's Jira. For this purpose I added the custom fields to the time entry DTOs. It was a no brainer, since the code was already there, I just had to add the field. Apart from that I added a few #derive Clone annotations. 

One more change I had to make: I had to comment out some #![forbid(private_in_public)] declaration. I don't know why this broke my compile, but it was an issue for me.

This whole thing was part of my first Rust project, and I have to admit this is my first pull request for some open source project, but I hope it's useful! If you think I missed something I'll try to fix it of course!

### CODE REVIEW

**Comment by taladar** [comment]
> One more change I had to make: I had to comment out some #![forbid(private_in_public)] declaration. I don't know why this broke my compile, but it was an issue for me.

This lint was recently removed and replaced by the lints described here https://rust-lang.github.io/rfcs/2145-type-privacy.html#private-in-public-lints

**Comment by taladar** [comment]
I will have a closer look at your changes tomorrow and then most likely release a new version. From a first glance nothing looks too complex.

**Comment by taladar** [comment]
I have now published 0.1.10 which includes your changes.

**Comment by michael-fuchs** [comment]
Hi Matthias! Thank you very much! That was quick! :-)

**Pull request merged**
